#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

#biom summarize table
biom summarize-table -i ~/otus3/otu_table.biom -o otu3_table_summary.txt

# deativating environment
source deactivate
