#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# picking OTUs
echo "picking OTUs"
pick_closed_reference_otus.py -i ~/slout/seqs.fna -r ~/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta -o otus3 -t SILVA_128_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt

# deactivating envrionment
source deactivate
