#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

#summarize_taxa
summarize_taxa.py -i ~/otus3/otu_table.biom -L 2 -o ~/stats/summarize_taxa2

# deactivating environment
source deactivate

